[23기 최민] Add: 카카오 소셜로그인 기능, 로그인 데코레이터 추가
wecode-bootcamp-korea/23-2nd-MAEILYHOTEL-backend pull request #3
Opened 2021-08-19 02:01 UTC by Min-Ch

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 카카오 로그인 기능, 데코레이터 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- 카카오 인가 코드를 받아서 카카오에서 토큰을 받고 그 토큰으로 유저 정보를 받아 로그인 기능 구현
- 로그인 데코레이터 기능 추가
- 프론트와 함께 로그인 성공

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-20 01:00 UTC, Min-Ch commented
![스크린샷 2021-08-20 오전 9 49 12](https://user-images.githubusercontent.com/84912594/130162582-d8fd4b65-27ad-4a7e-845a-5216230a2ff0.png)

unittest 결과입니다

2021-08-20 01:43 UTC, lordmyshepherd requested changes

2021-08-20 01:43 UTC, lordmyshepherd commented on users/views.py
> +            kakao_json = kakao_token_request.json()
소셜로그인 잘 구현해주셨네요~~ line 13~22 코드는 프론트에서 해야되는 기능이라고 보시면 됩니다.
`access_token` 발급까지는 프론트에서 하고 line23 이후에 코드만 백엔드에서 수행하면 됩니다.
```suggestion
```
즉, kakao_access_token을 frontend에서 header를 통해서 받올 수 있도록 구현해주세요~

2021-08-20 01:43 UTC, lordmyshepherd commented on users/views.py
> +            )
requests 모듈을 사용하실 때에는 timeout 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 생깁니다.

`timeout` 옵션을 추가해보세요~
```suggestion
            profile_request = requests.get(    
                "https://kapi.kakao.com/v2/user/me",
                headers = {"Authorization" : f"Bearer {kakao_json['access_token']}"}
            )
```

2021-08-20 01:43 UTC, lordmyshepherd commented on users/views.py
> +            )
변수에 담기는 값을 명확하게 작성해주세요~
requests.get() 호출시 요청에 대한 응답이 반환되므로 `response` 변수에 담아주시는게 좋습니다.

```suggestion
            response = requests.get(    
                "https://kapi.kakao.com/v2/user/me",
                headers = {"Authorization" : f"Bearer {kakao_json['access_token']}"}
            )
```

2021-08-20 01:43 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({"message" : "INVALID_TOKEN"}, status = 400)
이부분의 에러 처리는 status code로 처리하도록 수정해주세요~

2021-08-20 01:43 UTC, lordmyshepherd commented on users/views.py
> +                )
`get_or_create()` method를 사용하신 것은 👍 
다만 위와 같은 방법으로 작성할 경우에 예상치 못한 버그가 발생할 수 있을 것 같습니다.
get_or_create()하는 기준이 email, nickname, point ... 를 전부 기준으로 잡게되면, point 값이 달라지거나, nickname이 달라지면 새로운 유저가 생성되게 됩니다.

이런 문제가 발생하지 않게 만들려면 어떻게 수정해야 될까요?

2021-08-20 01:43 UTC, lordmyshepherd commented on users/tests.py
> +    def test_kakao_signin_new_user_success(self, mocked_requests):
`user/views.py`에서 피드백 내용 반영해하신 후에 테스트코드도 맞게 수정부탁드려요~

2021-08-22 09:38 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-08-22 09:39 UTC, merged