[23기 박병주] Add: 숙소 리스트 API
wecode-bootcamp-korea/23-2nd-MAEILYHOTEL-backend pull request #5
Opened 2021-08-20 09:13 UTC by byoungjupark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 지역별, 숙소타입별 필터링
- 예약 가능한 날짜별 필터링
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-22 11:52 UTC, lordmyshepherd reviewed
이번주에 구현해야되는 기능이 많으면, 추후에 수정하겠다고 코멘트 남겨주세요~

2021-08-22 11:52 UTC, lordmyshepherd commented on stays/views.py
> +                is_available = Case(When(remain = 0), then = False, default = True)).exclude(is_available= False)
이 문제를 해결하시다니 정말 👍👍👍
이번 코드는 문제해결 했던 방법 꼭 블로깅 하셔서 취업하실때 사용하시면 너무나도 좋을 것 같네요~

지금 코드도 너무 좋지만 피드백을 드리자면, 아래와 같은 방향으로 `line34~39` 코드를 수정해보시면 어떨까요?

sql 쿼리문 자체도 좀 더 간결해지고 가독성도 좋아질 것 같아요~ (지금까지 작성하신 것도 사실 대단하기 때문에, 기능 구현이 많이 남았으면 다음으로 수정을 미루셔도 됩니다! 코멘트 남겨주세요~)

```suggestion
        stays = Staytype.objects.annotate(
            total_room_count  = Sum('room__quantity'),
            booked_room_count = Subquery(
                Staytype.objects.annotate(booked_count = Count('room__book__id', filter=(q1| q2| q3))).filter(pk = OuterRef('pk')).values('booked_count')
            ),
            is_available = Case(
                When(total_room_count__gte = F('booked_room_count'), then=True), 
                default = False, 
                output_field = IntegerField()
            )
        ).exclude(is_available= False)
```

2021-08-22 11:52 UTC, lordmyshepherd commented on stays/views.py
> +            q3 = Q(room__book__check_in__lte = check_in, room__book__check_out__gte = check_out)
해당 케이스면 모든 케이스에서 필터링 가능한가요?
```suggestion
            q1 = Q(room__book__check_in__lte = check_in, room__book__check_out__gte = check_in)
            q2 = Q(room__book__check_in__lte = check_out, room__book__check_out__gte = check_out)
            q3 = Q(room__book__check_in__lte = check_in, room__book__check_out__gte = check_out)
```

만약에 모든 케이스를 커버하지 못한다면 아래와 같은 방향으로 조건을 어떤지 고민해보시면 좋을 것 같습니다. (추후 리펙토링할 때 수정해주세요~)

```python
q1 = Q(room__book__check_out__range = [check_in, check_out])
q1 = Q(room__book__check_in__range = [check_in, check_out])
q3 = Q(room__book__check_in__lte = check_in, room__book__check_out__gte = check_out)

```

2021-08-22 11:52 UTC, lordmyshepherd commented on stays/views.py
> +                    "image_url" : stay.staytypeimage_set.all()[0].image_url,
이부분은 위에서 `stays` 목록을 가져올 때, `prefetch_related` method를 사용하면 쿼리 수를 줄여볼 수 있을 것 같네요~

2021-08-22 11:52 UTC, lordmyshepherd commented on stays/tests.py
> +class StaytypeListTest(TestCase):
테스트 코드도 잘 작성해주셨습니다!!

다만 다음에 작성하실때는 더많은 케이스의 데이터를 생성하고 값을 비교하는게 더욱 정확할 것 같습니다~ (추후 수정)

2021-08-22 11:53 UTC, lordmyshepherd commented
컨플릭트 해결해주세요~

2021-08-22 15:24 UTC, byoungjupark commented on stays/views.py
> +                is_available = Case(When(remain = 0), then = False, default = True)).exclude(is_available= False)
병민님과 같은 팀원 민님의 도움으로 만들 수 있었습니다. 정말 감사드려요!!! 리뷰 토대로 리팩토링 했습니다.

2021-08-22 15:37 UTC, byoungjupark commented on stays/views.py
> +            q3 = Q(room__book__check_in__lte = check_in, room__book__check_out__gte = check_out)
다시 생각해보니 아래와 같은 경우에 누락됩니다. (check_in < room__book__check_in,out <check_out)
예)
room__book__check_in = 7/31, room__book__check_out = 8/2
check_in = 7/30, check_out = 8/4
다른 경우의 수는 추후에 생각해보도록 하고, 조언해주신 조건으로 우선 수정하였습니다

2021-08-22 15:37 UTC, byoungjupark commented on stays/tests.py
> +class StaytypeListTest(TestCase):
위의 누락되는 날짜 필터링을 확인하고자 예약 객체를 추가해보았습니다

2021-08-22 15:39 UTC, byoungjupark commented
날짜 필터링 경우의 수는 추후에 조금 더 생각해보도록 하겠습니다! 다른 부분들은 리뷰토대로 수정했고, 컨플릭트 해결했습니다 :)

2021-08-23 01:17 UTC, lordmyshepherd requested changes

2021-08-23 01:17 UTC, lordmyshepherd commented on stays/views.py
> +                        default = False
Case문에서 total_room_count가 예약된 room count보다 많을 경우 예약 가능으로 해줘야되는거 아닌가요??

```suggestion
                    is_available = Case(
                        When(total_room_count__gt = F('booked_room_count'), then = True), 
                        default = False
```

2021-08-23 03:43 UTC, byoungjupark commented on stays/views.py
> +                        default = False
total_room_count = booked_room_count 일 경우, sold out으로 생각해서 두 값이 같은 조건문으로 작성하였습니다.
이러한 숙소들은 is_available 값이 True가 되고 exclude 하는 방식으로 작성했습니다. 
다시 생각해보니 is_available 필드 자체와 반대되는 의미를 지니게 되네요.
병민님 말씀대로 gt로 수정하여 예약가능한 숙소들은 is_available 값이 True가 되도록 하였습니다.

2021-08-23 05:16 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-08-23 05:16 UTC, merged