[23기 최민] Add: 상세페이지 달력 기능 구현
wecode-bootcamp-korea/23-2nd-MAEILYHOTEL-backend pull request #6
Opened 2021-08-20 11:19 UTC by Min-Ch

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-23 10:01 UTC, lordmyshepherd requested changes

2021-08-23 10:01 UTC, lordmyshepherd commented on stays/views.py
> +    @query_debugger
디버깅용 데코레이터는 개발 용도로만 사용하셔야 합니다! 붙여서 배포하게되면 성능 저하 이슈가 생깁니다!

2021-08-23 10:01 UTC, lordmyshepherd commented on stays/views.py
> +            return JsonResponse({"message":"INVALID_ID"}, status=404)
if문 다음에는 한 줄 띄워주세요~

```suggestion
        if not Staytype.objects.filter(id = stay_id).exists():
            return JsonResponse({"message":"INVALID_ID"}, status=404)
            
```

2021-08-23 10:01 UTC, lordmyshepherd commented on core/utils.py
> +import pandas
불필요한 모듈은 import 하지 않도록 수정해주세요~

2021-08-23 10:01 UTC, lordmyshepherd commented on core/utils.py
> +    return price
해당 부분은 `Staytype`에만 사용되는 함수이므로 Staytype 모델의 method로 옮기는게 좋을 것 같습니다.
참고로 함수명은 동사로 시작해야 됩니다. 예) `get_discount_price`

2021-08-23 10:01 UTC, lordmyshepherd commented on stays/views.py
> +        date_list = pandas.date_range(today, periods = 30).to_pydatetime().tolist()
```python
dates = [start_date + timedelta(i) for i in range((end_date - start_date).days)]
```

2021-08-23 10:01 UTC, lordmyshepherd commented on stays/views.py
> +            price = discount_one_price(price=price, date=date)
```python
price = StayType.get_discount_one_price(price, date)
```

2021-08-23 11:49 UTC, Min-Ch commented
유닛테스트
<img width="665" alt="스크린샷 2021-08-23 오후 8 48 45" src="https://user-images.githubusercontent.com/84912594/130442284-817196d7-4414-453c-9cfa-b454c8375862.png">

통신결과입니다
<img width="1003" alt="스크린샷 2021-08-23 오후 8 48 21" src="https://user-images.githubusercontent.com/84912594/130442322-df2cc2d2-92ac-432f-8b74-fedbfe8efb52.png">

2021-08-24 01:11 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-08-24 01:44 UTC, merged