[23기 박병주] Add: 회원등급 PATCH API
wecode-bootcamp-korea/23-2nd-MAEILYHOTEL-backend pull request #9
Opened 2021-08-23 06:30 UTC by byoungjupark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 약관동의에 따른 회원등급 변경 기능 구현
		 
## 수정 사항들 자세한 내용
- 등급 silver와 약관동의 False 또는 등급 gold와 약관동의 True 일 때만 변경 가능
- 이 외의 경우 에러 처리

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-24 02:14 UTC, lordmyshepherd requested changes

2021-08-24 02:14 UTC, lordmyshepherd commented on stays.csv
> +카테고리,숙소이름,주소,Latitude,Longitude,설명,시설,숙소이미지,객실이름,인원,객실 수,객실이미지,대실/숙박,가격,체크인,체크아웃
csv 파일은 github에 올라오지 않도록 gitignore에 추가해주세요.

2021-08-24 02:14 UTC, lordmyshepherd commented on users/views.py
> +            request.user.agreement = eval(data["agreement"])
`argreement`, `userlevel`로 들어오는 값은 뭐가 들어오나요?

2021-08-24 03:32 UTC, byoungjupark commented on users/views.py
> +            request.user.agreement = eval(data["agreement"])
agreement는 요청시 문자열 타입의 True 또는 False로 들어옵니다. 약관동의 필드값으로 들어갈 값들입니다.
userlevel은 회원등급의 id로 uselevel =1은 실버 등급, userlevel = 2는 골드 등급으로 들어옵니다.

유저가 약관동의를 할 경우(True), 회원등급이 골드(userlevel = 2)로 됩니다. 약관동의를 하지 않을 경우(False), 회원등급은 실버(userlevel = 1)가 됩니다.
요청시 True와 실버인 경우 또는 False와 골드인 경우는 잘못된 요청으로 위와 같은 에러처리를 하였습니다.

2021-08-24 03:32 UTC, byoungjupark commented on stays.csv
> +카테고리,숙소이름,주소,Latitude,Longitude,설명,시설,숙소이미지,객실이름,인원,객실 수,객실이미지,대실/숙박,가격,체크인,체크아웃
네!

2021-08-25 01:35 UTC, lordmyshepherd commented on users/views.py
> +            request.user.agreement = eval(data["agreement"])
👍

2021-08-25 01:35 UTC, lordmyshepherd commented
LGTM 👍

2021-08-25 01:35 UTC, merged